First try to a working script
Signed-off-by: Georgios Tsotsos <tsotsos@gmail.com>

diff --git a/git-iam b/git-iam
--- a/git-iam
+++ b/git-iam
@@ -129,27 +129,69 @@ dump_database(){
 	fi;
 
 }
+# import database files
+# import_sql host port user password database branch
+import_sql(){
+	official_schema=$(pwd)"/databases/${6}_schema.official.sql"
+	schema=$(pwd)"/databases/${6}_schema.sql"
+	official_content=$(pwd)"/databases/${6}_content.official.sql"
+	content=$(pwd)"/databases/${6}_content.sql"
+	#schema
+	if [ -f $official_schema ]; then
+		drop_tables $1 $2 $3 $4 $5
+		import_database $1 $2 $3 $4 $5 $official_schema
+	elif [ -f $schema ]; then
+		read -p "There is not official database schema, do you want to import experimental ?  (y/n)" yn
+		case $yn in 
+			y|Y )
+				drop_tables $1 $2 $3 $4 $5
+				import_database $1 $2 $3 $4 $5 $schema
+			;;
+			n|N )
+			break
+			;;
+		esac
+	else
+		echo "Couldn't find a proper sql file to import"
+	fi
+	#content
+	if [ -f $official_content ]; then
+		import_database $1 $2 $3 $4 $5 $official_content
+	elif [ -f $content ]; then
+		read -p "There is not official database content, do you want to import experimental ?  (y/n)" yn
+		case $yn in 
+			y|Y )
+				import_database $1 $2 $3 $4 $5 $content
+			;;
+			n|N )
+			break
+			;;
+		esac
+	else
+		echo "Couldn't find a proper sql file to import"
+	fi
+}
 # Creates database and assign privileges for each branch
 create_db_foreach_branch(){
 	current=$(git rev-parse --abbrev-ref HEAD)
 	for branch in $(git branch | cut -c 3-); do
 		git checkout "$branch" >/dev/null 2>&1
-		official_schema=$(pwd)"/database/$5_${branch}_schema.official.sql"
-		schema=$(pwd)"/database/$5_${branch}_schema.sql"
-		official_content=$(pwd)"/database/$5_${branch}_content.official.sql"
-		content=$(pwd)"/database/$5_${branch}_content.sql"
+		official_schema=$(pwd)"/database/${branch}_schema.official.sql"
+		schema=$(pwd)"/database/${branch}_schema.sql"
+		official_content=$(pwd)"/database/${branch}_content.official.sql"
+		content=$(pwd)"/database/${branch}_content.sql"
 		#schema
 		if [ -f $official_schema ]; then
-			create_database $1 $2 $3 $4 "$5_$branch"
-			assign_privileges $1 $2 $3 $4 "$5_$branch" $5
-			import_database $1 $2 $3 $4 "$5_$branch" $official_schema
+			create_database $1 $2 $3 $4 "$branch"
+			assign_privileges $1 $2 $3 $4 "$branch" $5
+			import_database $1 $2 $3 $4 "$branch" $official_schema
 		elif [ -f $schema ]; then
 			read -p "There is not official database schema, do you want to import experimental ? - its not safe! (y/n)" yn
 			case $yn in 
 				y|Y )
-				create_database $1 $2 $3 $4 "$5_$branch"
-				assign_privileges $1 $2 $3 $4 "$5_$branch" $5
-				import_database $1 $2 $3 $4 "$5_$branch" $schema
+				create_database $1 $2 $3 $4 "$branch"
+				assign_privileges $1 $2 $3 $4 "$branch" $5
+				import_database $1 $2 $3 $4 "$branch" $schema
 				;;
 				n|N )
 				break
@@ -239,64 +281,37 @@ EOL
 			echo "Cool!"
 			echo "Your repository is setting also all folders,files and permissions of drupal, please add/commit to git"
 		;;
-		add-db|-adb )
+		database|-db )
 			dump_database $DATABASE_SERVER $DATABASE_PORT $DATABASE_USER $DATABASE_PASSWORD $DATABASE_NAME
-			#git add -v $DATABASE_NAME.sql
 		;;
-		new-branch-db|-nb )
-		if [ -n "$SECOND" ]; then
-			timestamp=$(date +"%s")
-			NEW_BRANCH=$(echo $SECOND | awk '{ gsub("-","_",$SECOND); print tolower($SECOND) }')
-			NEW_DATABASE="${PROJECT_NAME}_${NEW_BRANCH}"
-			dump_database $DATABASE_SERVER $DATABASE_PORT $DATABASE_USER $DATABASE_PASSWORD $DATABASE_NAME "${timestamp}.sql"
-			echo "Dumping your database is finished"
-		#	git branch $NEW_BRANCH
-		#	git checkout $NEW_BRANCHE
-		echo "Mysql admin account (root) password:" 
-			read -s MYSQL_ADMIN_PASS
-			create_database $DATABASE_SERVER $DATABASE_PORT $DATABASE_ADMIN $MYSQL_ADMIN_PASS $PROJECT_NAME
-		#	echo "Your new branch \"$NEW_BRANCH\" and database are ready!"
-		else
-			echo "Please select a name for the new branch"
-			echo "The syntax is: git iam {[-nb] or [--new-branch]} [the name]"
-		fi;
-		;;
-		commit-db|-c )
-			dump_database $DATABASE_NAME $DATABASE_USER $DATABASE_PASSWORD $DATABASE_SERVER $DATABASE_PORT
-			git commit "${*:2}"
-		;;
-		pull|-p )
-		current=$(git rev-parse --abbrev-ref HEAD)
-			for branch in $(git branch | cut -c 3-); do
-				git checkout "$branch" >/dev/null 2>&1
-				if [ -f $(pwd)"/$PROJECT_NAME"_"$branch.sql" ]; then
-					echo ok!
-				else
-					echo not ok
-				fi;
-			done
-			echo "--------------"
-			git checkout $current
-			#git pull --all
-			#update_database $DATABASE_NAME $DATABASE_USER $DATABASE_PASSWORD $DATABASE_SERVER $DATABASE_PORT $NEW_DATABASE
+		import-database|-idb )
+			check_database $DATABASE_SERVER $DATABASE_PORT $DATABASE_USER $DATABASE_PASSWORD $DATABASE_NAME
+			db="$?"
+			if [ "$db" -eq 1 ]; then
+				import_sql $DATABASE_SERVER $DATABASE_PORT $DATABASE_USER $DATABASE_PASSWORD $DATABASE_NAME $CURRENT_BRANCH
+			else
+				echo "no"
+			fi;
 		;;
 		drupal-modules| -dm)
 			$MYSQL -h$DATABASE_SERVER -P$DATABASE_PORT -u$DATABASE_USER -p$DATABASE_PASSWORD -e "select name,status from ${DATABASE_NAME}.system order by name;" > MODULES
 			;;
-		help|-h)
+		help|-h|*)
 		cat <<EOF
 This script is under GPL v3
-Copyright (c) 2014, Georgios Tsotsos <tsotsos@gmail.com>
+Copyright (c) 2014-2015, Georgios Tsotsos <tsotsos@gmail.com>
+Usage: $0 [-h or help]
 
-Usage: $0 [-h or help] [-b or branch] [-c or commit ]
-
--h|help		This is output.
+-h|help				This is output.
 		
--b|branch	Creates a new branch and commits the database dump.
+-im|import-project		Imports a whole new project with all branches and databases
 		
--c|commit	Commits the database dump file.
-		It can accept all the arguments of "git commit"
--p|pull		Pull all changes from server and then updates the database (experimental)
+-np|new-project			Creates a new project, downloads drupal etc.
+		
+-db|database			Creates a database dump under databases/
+		
+-idb|import-database	Imports a database dump (priority to official dumps)
+		
 EOF
 		;;
 esac
